server_connect_timeout: 5000
enforce_secure_profile: false
remote_ping_cache: -1
forge_support: true
player_limit: -1
permissions:
  admin:
  - bungeecord.command.server
  - bungeecord.command.list
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - bungeecord.command.kick
timeout: 30000
log_commands: false
network_compression_threshold: 256
online_mode: true
disabled_commands:
- disabledcommandhere
servers:
  lobby:
    motd: '&1lobbyeee'
    address: localhost:25565
    restricted: false
  # team01:
  #   motd: '&1Team01'
  #   address: localhost:25566
  #   restricted: false
  # team02:
  #   motd: '&1Team02'
  #   address: localhost:25567
  #   restricted: false
  # team03:
  #   motd: '&1Team03'
  #   address: localhost:25568
  #   restricted: false
  # team04:
  #   motd: '&1Team04'
  #   address: localhost:25569
  #   restricted: false
  # team05:
  #   motd: '&1Team05'
  #   address: localhost:25570
  #   restricted: false
  # team06:
  #   motd: '&1Team06'
  #   address: localhost:25571
  #   restricted: false
  # team07:
  #   motd: '&1Team07'
  #   address: localhost:25572
  #   restricted: false
  # team08:
  #   motd: '&1Team08'
  #   address: localhost:25573
  #   restricted: false
  # team09:
  #   motd: '&1Team09'
  #   address: localhost:25574
  #   restricted: false
  # team10:
  #   motd: '&1Team10'
  #   address: localhost:25575
  #   restricted: false
listeners:
- query_port: 25577
  motd: '&1CosmicCraft'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - lobby
  bind_local_address: true
  host: 0.0.0.0:25577
  max_players: 100
  tab_size: 60
  force_default_server: true
ip_forward: true
remote_ping_timeout: 5000
prevent_proxy_connections: false
groups:
  Djbrown_:
  - admin
  Xbird_:
  - admin
connection_throttle: 4000
stats: 260d83f6-57c0-4c28-9958-06f6368972fa
connection_throttle_limit: 3
log_pings: true
